name: Build, test, package

on: [push,pull_request]

concurrency:
  group: '${{ github.workflow }}@${{ github.head_ref || github.run_id }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.2
    with: 
      itk-module-deps: RTK@master

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@main
    with:
      # Disable RTK_BUILD_APPLICATIONS to reduce compilation time
      cmake-options: '-DRTK_BUILD_APPLICATIONS:BOOL=OFF'
      python3-minor-versions: ${{ github.event_name == 'pull_request' && '["11"]' || '["9","10","11"]' }}
      itk-python-package-tag: 'c9c8130258a0cbb7d29ee1047d3b8692540e26cf'
      itk-module-deps: RTKConsortium/RTK@f7595babde69005a5df98a294c47dedfd579c171
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
