name: Build, test, package

on: [push,pull_request]

concurrency:
  group: '${{ github.workflow }}@${{ github.head_ref || github.run_id }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.0
    with: 
      itk-module-deps: RTK@96e7b8c

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.0
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
